In [1]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

   Ответ: не определены ни $A \cdot B$, ни $B \cdot\ A$ - $(rowsA \neq colsB, colsA \neq rowsB )$
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

   Ответ: определено $A \cdot B$ $(3 \times 2)$ , $B \cdot A$ не определено - $(colsB \neq rowsA)$
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

   Ответ: определены $A \cdot B$ $(8 \times 8)$ и $B \cdot A$ $(3 \times 3)$
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
   
   Ответ: определены $A \cdot B$ и $B \cdot A$ $(4 \times 4)$


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B = \begin{pmatrix}1+4 & -2-1\\ 3+0 & 0+5 \end{pmatrix} = \begin{pmatrix}5 & -3\\ 3& 5 \end{pmatrix}$

$A \cdot B = \begin{pmatrix}
(1 \cdot 4 + -2 \cdot 0) & (1 \cdot -1 + -2 \cdot 5) \\
(3 \cdot 4 + 0 \cdot 0) & (3 \cdot -1 + 0 \cdot 5)
\end{pmatrix} = \begin{pmatrix}4 & -11 \\ 12 & -3 \end{pmatrix}$


In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])


print('Sum=\n', A + B); print('\n\nMultiply=\n', np.dot(A, B))

Sum=
 [[ 5 -3]
 [ 3  5]]


Multiply=
 [[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C
=\begin{pmatrix} 3 & 21 \\ 9 & -18 \end{pmatrix}
-\begin{pmatrix} 0 & 10 \\4 & -2 \end{pmatrix}
+\begin{pmatrix} 8 & -16 \\ 4 & 4 \end{pmatrix}
=\begin{pmatrix} 3-0+8 & 21-10-16 \\ 9-4+4 & -18+2+4 \end{pmatrix}
=\begin{pmatrix} 11 & -5 \\ 9 & -12 \end{pmatrix}
$


In [3]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print('3A=\n', 3 * A); print('\n\n2B=\n', 2 * B); print('\n\n4C=\n', 4 *C); 
print('\n\n3A-2B+4C=\n', 3 * A - 2 * B + 4 * C)

3A=
 [[  3  21]
 [  9 -18]]


2B=
 [[ 0 10]
 [ 4 -2]]


4C=
 [[  8 -16]
 [  4   4]]


3A-2B+4C=
 [[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T} = \begin{pmatrix} 4 & 5 & 2 \\1 & -2 & 3 \end{pmatrix}$

$AA^{T}
=\begin{pmatrix}
(4*4+1*1) & (4*5+1*-2) & (4*2+1*3) \\
(5*4-2*1) & (5*5+-2*-2) & (5*2-2*3) \\
(2*4+3*1) & (2*5-2*3) & (2*2+3*3)
 \end{pmatrix}
 =\begin{pmatrix}
17 & 18 & 11 \\ 18 & 29 & 4 \\ 11 & 4 & 13
 \end{pmatrix}
$

$A^{T}A=
\begin{pmatrix}
(4*4+5*5+2*2) & (4*1-5*2+2*3) \\
(1*4-2*5+3*2) & (1*1+-2*-2+3*3)
\end{pmatrix}
=\begin{pmatrix}
45 & 0 \\ 0 & 14
\end{pmatrix}
$

In [4]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print('A*A_T=\n', np.dot(A, A.T)); print('\n\nA_T*A=\n', np.dot(A.T, A)); 

A*A_T=
 [[17 18 11]
 [18 29  4]
 [11  4 13]]


A_T*A=
 [[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
from typing import List

def multiply_matrix(a: List[List[float]], b: List[List[float]]):

    if len(a[0]) != len(b):
        return -1

    result = []
    for row, items in enumerate(a):
        result.append([])
        for column_id in range(len(a)):
            summ = 0
            for row_id, item in enumerate(items):
                summ += item * b[row_id][column_id]
            result[row].append(summ)
    
    return result

A = [[4, 1], [5, -2], [2, 3]]
A_T = [[4, 5, 2], [1, -2, 3]]

print('A * A_T =', multiply_matrix(A, A_T))
print('A_T * A = ', multiply_matrix(A_T, A))


A * A_T = [[17, 18, 11], [18, 29, 4], [11, 4, 13]]
A_T * A =  [[45, 0], [0, 14]]
